# Generated by Django 4.1.7 on 2023-09-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_templates_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Complete',
            new_name='complete',
        ),
    ]
